export const LOGIN_EMAIL = 'LOGIN_EMAIL'
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD'

export const REGISTER_EMAIL = 'REGISTER_EMAIL'
export const REGISTER_USER_DATA = 'REGISTER_USER_DATA'
export const REGISTER_PASSWORD = 'REGISTER_PASSWORD'

export const SUCCESS = 'success'
