export const GET_FRIENDS = 'GET_FRIENDS'
export const SET_FETCHING_FRIENDS = 'SET_LOADING_FRIENDS'
export const SET_FETCHING_FRIENDS_FINISHED = 'SET_LOADING_FRIENDS_FINISHED'
export const SET_FRIENDS = 'SET_FRIENDS'
export const SET_FRIEND_REQUESTS = 'SET_FRIEND_REQUESTS'

