export const GET_CHATS = 'GET_CHATS'
export const SET_FETCHING_CHATS = 'SET_FETCHING_CHATS'
export const SET_FETCHING_CHATS_FINISHED = 'SET_FETCHING_CHATS_FINISHED'
export const SET_CHATS = 'SET_CHATS'
